import os
import sys
import argparse
import shutil
import time
import json
from glob import glob
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import cv2


_BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _BASE_DIR)
from utils.metrics_helper import rgb_metrics, depth_metrics, pose_metrics, pose_metrics_detailed
    
def metric_single(gt, render):
    """Calculates the PSNR between color and depth folders of images.

    Args:
        gt: The base folder containing 'color' and 'depth' subfolders.
        render: The comparison folder containing 'color' and 'depth' subfolders.

    Returns:
        None.
    """

    if os.path.exists(os.path.join(render, 'eval')):
        render = os.path.join(render, 'eval')

    psnr, ssim, lpips, pl, sl, ll = rgb_metrics(gt, render)
    rmse, rl = depth_metrics(gt, render)
    gp_path = os.path.join(render, 'gt_train_w2c.txt')
    ep_path = os.path.join(render, 'est_w2c.txt')
    # align_gt = 'cmp/Fusion/results/{}/eval/gt_train_w2c.txt'.format(render.split('/')[-2])
    ate, gt_pts, est_pts = pose_metrics(gp_path, ep_path, None)
    
    return {'rgb': [psnr, ssim, lpips], 'depth': [rmse], 'pose': [ate], 'lists': [pl, sl, ll, rl], 'traj': [gt_pts, est_pts]}


def plot_sequences(seq1, seq2, seq3, seq4, labels, save_path):
    """
    Plots four sequences in a single line plot and saves the plot to a specified path.

    Args:
        seq1, seq2, seq3, seq4: Lists or arrays containing the sequences to be plotted.
        labels: A list of strings containing the labels for each sequence.
        save_path: The file path where the plot will be saved.
    """
    plt.figure(figsize=(10, 6))
    plt.plot(seq1, label=labels[0])
    plt.plot(seq2, label=labels[1])
    plt.plot(seq3, label=labels[2])
    plt.plot(seq4, label=labels[3])
    plt.xlabel('Index')
    plt.ylabel('Value')
    plt.title('Sequence Comparison')
    plt.legend()
    plt.grid(True)
    plt.savefig(save_path)
    plt.close()


def plot_3d_trajectories(gt, est, ate, save_path):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    
    ax.plot(gt[0], gt[1], gt[2], color='blue', label='GT')
    ax.plot(est[0], est[1], est[2], color='red', label='Estimate')
    
    ax.legend()
    
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    plt.title(f'ATE: {ate:.3f}')
    plt.savefig(save_path)


def export_mp4_from_png_folder(image_folder: str, video_path: str, fps: int = 30):
    images = sorted(glob(os.path.join(image_folder, "*.png")))
    if not images:
        print(f"[calc_metrics] No pngs found in: {image_folder}")
        return
    frame0 = cv2.imread(images[0])
    if frame0 is None:
        print(f"[calc_metrics] Failed to read: {images[0]}")
        return
    height, width = frame0.shape[:2]
    os.makedirs(os.path.dirname(video_path) or ".", exist_ok=True)
    if os.path.exists(video_path):
        try:
            os.remove(video_path)
        except Exception:
            pass
    out = cv2.VideoWriter(video_path, cv2.VideoWriter_fourcc(*"mp4v"), float(fps), (width, height))
    if not out.isOpened():
        print(f"[calc_metrics] Failed to open VideoWriter: {video_path}")
        return
    try:
        for p in images:
            frame = cv2.imread(p)
            if frame is None:
                continue
            out.write(frame)
    finally:
        out.release()
    print(f"[calc_metrics] Saved video to: {video_path}")


def export_video_with_fallback(render_used: str, out_dir: str, seq: str, fps: int, tag: str = "") -> None:
    # True allframes requires plots_all generated by the SLAM run.
    plots_all_dir = os.path.join(render_used, "plots_all")

    if os.path.isdir(plots_all_dir) and _list_pngs(plots_all_dir):
        export_mp4_from_png_folder(plots_all_dir, os.path.join(out_dir, f"{seq}_allframes{tag}.mp4"), fps=fps)
        return
    print("[calc_metrics] True allframes mp4 requires eval/plots_all. Skipping allframes export.")


def _resolve_run_dir(render_path: str) -> str:
    p = os.path.abspath(render_path.rstrip("/"))
    return os.path.dirname(p) if os.path.basename(p) == "eval" else p


def _load_run_config(run_dir: str) -> dict:
    cfg_path = os.path.join(run_dir, "config_used.json")
    if not os.path.isfile(cfg_path):
        return {}
    try:
        with open(cfg_path, "r", encoding="utf-8") as f:
            cfg = json.load(f)
        return cfg if isinstance(cfg, dict) else {}
    except Exception:
        return {}


def _select_pose_eval(cfg: dict) -> dict:
    # Explicit pose_eval in the saved run config wins.
    pe = cfg.get("pose_eval", None)
    if isinstance(pe, dict):
        return {
            "metric": str(pe.get("metric", "ate")).lower(),
            "align_mode": str(pe.get("align_mode", pe.get("align", "se3"))).lower(),
            "rpe_delta": int(pe.get("rpe_delta", 1)),
        }

    return {"metric": "ate", "align_mode": "se3", "rpe_delta": 1}


def _list_pngs(folder: str) -> list[str]:
    return sorted(glob(os.path.join(folder, "*.png")))


def _list_ext(folder: str, ext: str) -> list[str]:
    return sorted(glob(os.path.join(folder, f"*.{ext}")))


def _has_any_depth_files(folder: str) -> bool:
    for ext in ("tiff", "tif", "png"):
        if _list_ext(folder, ext):
            return True
    return False


def _resolve_render_used(render: str) -> str:
    eval_dir = os.path.join(render, "eval")
    return eval_dir if os.path.exists(eval_dir) else render


def _preflight_paths(gt: str, render_used: str) -> None:
    gt_color = os.path.join(gt, "color")
    gt_depth = os.path.join(gt, "depth")
    render_color = os.path.join(render_used, "color")
    render_depth = os.path.join(render_used, "depth")
    render_est = os.path.join(render_used, "est_w2c.txt")
    render_gt = os.path.join(render_used, "gt_train_w2c.txt")

    if not os.path.isdir(gt_color):
        raise FileNotFoundError(f"GT color folder not found: {gt_color}")
    if not os.path.isdir(gt_depth):
        raise FileNotFoundError(f"GT depth folder not found: {gt_depth}")
    if not os.path.isdir(render_color):
        raise FileNotFoundError(f"Render color folder not found: {render_color}")
    if not os.path.isdir(render_depth):
        raise FileNotFoundError(f"Render depth folder not found: {render_depth}")
    if len(_list_pngs(gt_color)) == 0:
        raise FileNotFoundError(f"No GT color pngs found in: {gt_color}")
    if len(_list_pngs(render_color)) == 0:
        raise FileNotFoundError(
            f"No render color pngs found in: {render_color}\n"
            f"Tip: pass the correct run directory that contains eval/ (e.g. experiments/<group>/<seq>)."
        )
    # C3VD depth is typically .tiff (and depth_metrics expects tiff scaling).
    if len(_list_ext(gt_depth, "tiff")) == 0 and len(_list_ext(gt_depth, "tif")) == 0:
        if _has_any_depth_files(gt_depth):
            raise FileNotFoundError(
                f"GT depth exists but is not .tiff: {gt_depth}\n"
                f"Tip: current depth_metrics expects .tiff in GT and render depth folders."
            )
        raise FileNotFoundError(f"No GT depth .tiff files found in: {gt_depth}")
    if len(_list_ext(render_depth, "tiff")) == 0 and len(_list_ext(render_depth, "tif")) == 0:
        if _has_any_depth_files(render_depth):
            raise FileNotFoundError(
                f"Render depth exists but is not .tiff: {render_depth}\n"
                f"Tip: current depth_metrics expects .tiff in GT and render depth folders."
            )
        raise FileNotFoundError(f"No render depth .tiff files found in: {render_depth}")
    if not os.path.isfile(render_est):
        raise FileNotFoundError(f"Missing pose file: {render_est}")
    if not os.path.isfile(render_gt):
        raise FileNotFoundError(f"Missing pose file: {render_gt}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--gt", help="The base folder containing 'color' and 'depth' subfolders.")
    parser.add_argument("--render", help="The comparison folder containing 'color' and 'depth' subfolders.")
    parser.add_argument("--test_single", help="Test single metric function.", action='store_true')
    parser.add_argument("--name", help="Name of record folder", default='')
    parser.add_argument(
        "--save_json",
        help="Save single-sequence metrics to <render>/metrics.json (or --json_path).",
        action="store_true",
    )
    parser.add_argument(
        "--json_path",
        help="Optional output path for --save_json.",
        default=None,
    )
    parser.add_argument(
        "--save_video",
        help="Save videos from existing eval/plots_all, eval/plots, and eval/color* folders.",
        action="store_true",
    )
    parser.add_argument("--video_fps", type=int, default=30)
    parser.add_argument(
        "--video_tag",
        default="",
        help="Optional suffix appended to output mp4 filenames (e.g. 'v2' -> *_v2.mp4).",
    )
    args = parser.parse_args()


    if args.test_single:
        render_used = _resolve_render_used(args.render)
        try:
            _preflight_paths(args.gt, render_used)
        except Exception as e:
            seq = os.path.basename(os.path.abspath(args.render.rstrip("/")))
            print(f"[calc_metrics] Preflight failed for seq={seq}")
            print(str(e))
            try:
                candidates = []
                for root in glob(os.path.join("experiments", "*", seq)):
                    if os.path.isdir(root):
                        candidates.append(root)
                if candidates:
                    print("[calc_metrics] Found candidate render dirs:")
                    for c in sorted(candidates):
                        print(" -", c)
            except Exception:
                pass
            sys.exit(2)

        run_dir = _resolve_run_dir(args.render)
        cfg = _load_run_config(run_dir)
        pose_eval = _select_pose_eval(cfg)
        print("[calc_metrics] pose_eval:", pose_eval)

        metrics = metric_single(args.gt, args.render)
        print("PSNR: ", metrics['rgb'][0])
        print("SSIM: ", metrics['rgb'][1])
        print("LPIPS: ", metrics['rgb'][2])
        print("RMSE: ", metrics['depth'][0])
        gp_path = os.path.join(render_used, 'gt_train_w2c.txt')
        ep_path = os.path.join(render_used, 'est_w2c.txt')
        pose = pose_metrics_detailed(
            gp_path,
            ep_path,
            metric=pose_eval["metric"],
            align_mode=pose_eval["align_mode"],
            rpe_delta=pose_eval["rpe_delta"],
        )
        print(f"{pose['score_name']}: ", pose["score"])
        plot_sequences(np.array(metrics['lists'][0])/10, metrics['lists'][1], metrics['lists'][2], metrics['lists'][3], ['PSNR/10', 'SSIM', 'LPIPS', 'RMSE'], 'metrics.png')
        plot_3d_trajectories(pose["gt_pts"], pose["est_pts_aligned"], float(pose.get("score", 0.0)), 'traj.png')
        if args.save_json:
            out_path = args.json_path or os.path.join(args.render, "metrics.json")
            payload = {
                "gt": args.gt,
                "render": args.render,
                "render_used": render_used,
                "psnr": float(metrics["rgb"][0]),
                "ssim": float(metrics["rgb"][1]),
                "lpips": float(metrics["rgb"][2]),
                "rmse": float(metrics["depth"][0]),
                "pose_metric": str(pose["score_name"]),
                "pose_score": float(pose["score"]),
                "pose_align_mode": str(pose["align_mode"]),
                "pose_scale": float(pose["scale"]),
                "ate_mean": None if pose.get("ate_mean", None) is None else float(pose["ate_mean"]),
                "rpe_trans_mean": None if pose.get("rpe_trans_mean", None) is None else float(pose["rpe_trans_mean"]),
                "rpe_trans_rmse": None if pose.get("rpe_trans_rmse", None) is None else float(pose["rpe_trans_rmse"]),
            }
            timing_path = os.path.join(args.render, "timing.json")
            if os.path.isfile(timing_path):
                try:
                    with open(timing_path, "r", encoding="utf-8") as tf:
                        payload["timing"] = json.load(tf)
                except Exception as e:
                    payload["timing_error"] = str(e)
            if os.path.isfile(os.path.join(run_dir, "config_used.json")):
                payload["config_used_json"] = os.path.join(run_dir, "config_used.json")
                payload["pose_eval"] = pose_eval
            # Only create parent dirs if the render dir exists; avoid creating empty run folders.
            parent = os.path.dirname(out_path) or "."
            if parent != "." and not os.path.isdir(parent):
                raise FileNotFoundError(f"Output directory does not exist: {parent}")
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(payload, f, ensure_ascii=False, indent=2)
            print("Saved json to:", out_path)
        if args.save_video:
            render_norm = os.path.abspath(args.render.rstrip("/"))
            seq = os.path.basename(os.path.dirname(render_norm)) if os.path.basename(render_norm) == "eval" else os.path.basename(render_norm)
            tag = str(args.video_tag or "")
            if tag and (not tag.startswith("_")):
                tag = "_" + tag
            export_video_with_fallback(render_used, args.render, seq, fps=args.video_fps, tag=tag)
            # Keyframes mp4 stays anchored to eval/plots when present.
            plots_dir = os.path.join(render_used, "plots")
            if os.path.isdir(plots_dir) and _list_pngs(plots_dir):
                export_mp4_from_png_folder(
                    plots_dir,
                    os.path.join(args.render, f"{seq}_keyframes{tag}.mp4"),
                    fps=args.video_fps,
                )
            else:
                print("[calc_metrics] eval/plots missing/empty; skip *_keyframes.mp4")

            # Also export direct RGB render videos from eval/color* (useful for transient/static/blend).
            for sub, out_suffix in (
                ("color", "blend"),
                ("color_static", "static"),
                ("color_transient", "transient"),
            ):
                d = os.path.join(render_used, sub)
                if os.path.isdir(d) and _list_pngs(d):
                    export_mp4_from_png_folder(
                        d,
                        os.path.join(args.render, f"{seq}_{out_suffix}{tag}.mp4"),
                        fps=args.video_fps,
                    )
    else:
        record_dir = './records/' + time.strftime("%Y-%m-%d-%H-%M-%S ", time.localtime()) + args.name
        os.makedirs(record_dir, exist_ok=True)
        
        results = {"PSNR": [], "SSIM": [], "LPIPS": [], "RMSE": [], "ATE": []}
        seqs = os.listdir(args.render)
        if os.path.exists(os.path.join(args.render, seqs[0], 'config.py')):
            shutil.copy(os.path.join(args.render, seqs[0], 'config.py'), os.path.join(record_dir, 'config.py'))
        for seq in seqs:
            if not os.path.isdir(os.path.join(args.render, seq)):
                continue
            print("Processing: ", seq)
            seq_dir = os.path.join(args.render, seq)
            seq_gt = os.path.join(args.gt, seq)
            metrics = metric_single(seq_gt, seq_dir)
            if os.path.exists(os.path.join(args.render, seq, 'keyframes.avi')):
                shutil.copy(os.path.join(args.render, seq, 'keyframes.avi'), os.path.join(record_dir, f'{seq}.avi'))
            if os.path.exists(os.path.join(args.render, seq, 'runtimes.txt')):
                shutil.copy(os.path.join(args.render, seq, 'runtimes.txt'), os.path.join(record_dir, f'{seq}.txt'))
            plot_sequences(np.array(metrics['lists'][0])/10, metrics['lists'][1], metrics['lists'][2], metrics['lists'][3], ['PSNR/10', 'SSIM', 'LPIPS', 'RMSE'], os.path.join(record_dir, f'{seq}_metrics.png'))
            plot_3d_trajectories(metrics['traj'][0], metrics['traj'][1], metrics['pose'][0], os.path.join(record_dir, f'{seq}_traj.png'))

            results["PSNR"].append(metrics['rgb'][0])
            results["SSIM"].append(metrics['rgb'][1])
            results["LPIPS"].append(metrics['rgb'][2])
            results["RMSE"].append(metrics['depth'][0])
            results["ATE"].append(metrics['pose'][0])

        with open(os.path.join(record_dir, 'results.csv'), 'w') as f:
            f.write('Sequence,PSNR,SSIM,LPIPS,RMSE,ATE\n')
            for i, seq in enumerate(seqs):
                f.write(f"{seq},{results['PSNR'][i]},{results['SSIM'][i]},{results['LPIPS'][i]},{results['RMSE'][i]},{results['ATE'][i]}\n")
            f.write(f"Mean,{np.mean(results['PSNR'])},{np.mean(results['SSIM'])},{np.mean(results['LPIPS'])},{np.mean(results['RMSE'])},{np.mean(results['ATE'])}\n")
            f.write(f"Std,{np.std(results['PSNR'])},{np.std(results['SSIM'])},{np.std(results['LPIPS'])},{np.std(results['RMSE'])},{np.std(results['ATE'])}\n")
            
            print("Results saved to: ", os.path.join(record_dir, 'results.csv'))
